---

## Wait For Servers To Boot

- hosts: "mcs,mx"
  become: yes
  become_user: root
  gather_facts: no

  tasks:
    - name: "Waiting For Servers To Initialize"
      wait_for_connection:

## Bootstrap For Ansible

- hosts: "mcs,mx"
  become: yes
  become_user: root
  gather_facts: yes
  vars_files:
    - 'inventory/group_vars/distro/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }}.yml'

  pre_tasks:
    - name: "Bootstrapping System For Ansible"
      raw: '{{ pre_task }}'

## Include Sub Playbooks

- name: "Preparing The Servers"
  import_playbook: includes/prepare.yml

- name: "Setting Up Multi-Attach EBS Share"
  import_playbook: includes/share.yml

- name: "Installing MariaDB"
  import_playbook: includes/install.yml

- name: "Setting Up Cluster"
  import_playbook: includes/cluster.yml

- name: "Validating Installation"
  import_playbook: includes/validate.yml

- name: "Configuring MaxScale"
  import_playbook: includes/maxscale.yml
