---

boto: python3-boto3
columnstore_cnf: /etc/my.cnf.d/columnstore.cnf
gcc: gcc
git: git
gluster_repo: centos-release-gluster7
gluster_server: glusterfs-server
htop: htop
jemalloc: jemalloc
jq: jq
mariadb_backup: MariaDB-backup
mariadb_cs_engine: MariaDB-columnstore-engine
mariadb_client: MariaDB-client
mariadb_columnstore: MariaDB-columnstore-engine
mariadb_columnstore_cmapi: mariadb-columnstore-cmapi
mariadb_libs: mariadb-libs
mariadb_repo: /etc/yum.repos.d/mariadb.repo
mariadb_shared: MariaDB-shared
mariadb_server: MariaDB-server
mariadb_socket: /var/lib/mysql/mysql.sock
maxscale: maxscale
mlocate: mlocate
nano: nano
nfs_utils: nfs-utils
python_dev: platform-python-devel
pre_task: dnf -y install epel-release && dnf -y install glibc-locale-source glibc-langpack-en python3
python_mysql: python2-PyMySQL,python3-PyMySQL
python_requests: python3-requests
server_cnf: /etc/my.cnf.d/server.cnf
tar: tar
unzip: unzip
wget: wget
